// <auto-generated />
using System;
using Aihrly.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aihrly.Api.Migrations
{
    [DbContext(typeof(AihrlyDbContext))]
    [Migration("20260429142421_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aihrly.Api.Models.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssessmentComment")
                        .HasColumnType("text");

                    b.Property<int?>("AssessmentScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AssessmentUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssessmentUpdatedById")
                        .HasColumnType("integer");

                    b.Property<string>("CandidateEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CoverLetter")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("CultureFitComment")
                        .HasColumnType("text");

                    b.Property<int?>("CultureFitScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CultureFitUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CultureFitUpdatedById")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("integer");

                    b.Property<string>("InterviewComment")
                        .HasColumnType("text");

                    b.Property<int?>("InterviewScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("InterviewUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InterviewUpdatedById")
                        .HasColumnType("integer");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentUpdatedById");

                    b.HasIndex("CultureFitUpdatedById");

                    b.HasIndex("InterviewUpdatedById");

                    b.HasIndex("JobId", "CandidateEmail")
                        .IsUnique();

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.ApplicationNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("CreatedById");

                    b.ToTable("ApplicationNotes");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.StageHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChangedById")
                        .HasColumnType("integer");

                    b.Property<int>("FromStage")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ToStage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ChangedById");

                    b.ToTable("StageHistoryEntries");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alex.johnson@aihrly.test",
                            Name = "Alex Johnson",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "sam.patel@aihrly.test",
                            Name = "Sam Patel",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "jordan.lee@aihrly.test",
                            Name = "Jordan Lee",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.Application", b =>
                {
                    b.HasOne("Aihrly.Api.Models.Entities.TeamMember", "AssessmentUpdatedBy")
                        .WithMany()
                        .HasForeignKey("AssessmentUpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aihrly.Api.Models.Entities.TeamMember", "CultureFitUpdatedBy")
                        .WithMany()
                        .HasForeignKey("CultureFitUpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aihrly.Api.Models.Entities.TeamMember", "InterviewUpdatedBy")
                        .WithMany()
                        .HasForeignKey("InterviewUpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Aihrly.Api.Models.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssessmentUpdatedBy");

                    b.Navigation("CultureFitUpdatedBy");

                    b.Navigation("InterviewUpdatedBy");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.ApplicationNote", b =>
                {
                    b.HasOne("Aihrly.Api.Models.Entities.Application", "Application")
                        .WithMany("Notes")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aihrly.Api.Models.Entities.TeamMember", "CreatedBy")
                        .WithMany("NotesCreated")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.StageHistory", b =>
                {
                    b.HasOne("Aihrly.Api.Models.Entities.Application", "Application")
                        .WithMany("StageHistoryEntries")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aihrly.Api.Models.Entities.TeamMember", "ChangedBy")
                        .WithMany("StageChanges")
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("ChangedBy");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.Application", b =>
                {
                    b.Navigation("Notes");

                    b.Navigation("StageHistoryEntries");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Aihrly.Api.Models.Entities.TeamMember", b =>
                {
                    b.Navigation("NotesCreated");

                    b.Navigation("StageChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
